<a href="https://colab.research.google.com/github/AayushPaigwar/PMLT_LABS/blob/master/%5BMLT%5D_Pract_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf


tensor_a = tf.constant([[1, 2], [3, 4]], dtype=tf.float32)
tensor_b = tf.constant([[5, 6], [7, 8]], dtype=tf.float32)

print("Tensor A:")
print(tensor_a)
print("Tensor B:")
print(tensor_b)



In [ ]:
# Addition
tensor_add = tf.add(tensor_a, tensor_b)
print("\nAddition of Tensor A and Tensor B:")
print(tensor_add)



Addition of Tensor A and Tensor B:
tf.Tensor(
[[ 6.  8.]
 [10. 12.]], shape=(2, 2), dtype=float32)


In [ ]:
# Subtraction
tensor_subtract = tf.subtract(tensor_a, tensor_b)
print("\nSubtraction of Tensor A and Tensor B:")
print(tensor_subtract)



Subtraction of Tensor A and Tensor B:
tf.Tensor(
[[-4. -4.]
 [-4. -4.]], shape=(2, 2), dtype=float32)


In [ ]:
# Multiplication
tensor_multiply = tf.multiply(tensor_a, tensor_b)
print("\nMultiplication of Tensor A and Tensor B:")
print(tensor_multiply)



Multiplication of Tensor A and Tensor B:
tf.Tensor(
[[ 5. 12.]
 [21. 32.]], shape=(2, 2), dtype=float32)


In [ ]:
# Division
tensor_divide = tf.divide(tensor_a, tensor_b)
print("\nDivision of Tensor A and Tensor B:")
print(tensor_divide)


Division of Tensor A and Tensor B:
tf.Tensor(
[[0.2        0.33333334]
 [0.42857143 0.5       ]], shape=(2, 2), dtype=float32)
