<a href="https://colab.research.google.com/github/AayushPaigwar/PMLT_LABS/blob/master/%5BMLT%5DPract_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# !pip install tensorflow

In [ ]:
import tensorflow as tf

In [ ]:
m1 = tf.constant(3)
m2 = tf.constant(4)

In [ ]:
m1,m2

(<tf.Tensor: shape=(), dtype=int32, numpy=3>,
 <tf.Tensor: shape=(), dtype=int32, numpy=4>)

In [ ]:
m3 = tf.multiply(m1,m2)
m3

<tf.Tensor: shape=(), dtype=int32, numpy=12>

In [ ]:
m4 = tf.add(m1,m2)
m4

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
m5 = tf.subtract(m1,m2)
m5


<tf.Tensor: shape=(), dtype=int32, numpy=-1>

In [ ]:
m6 = tf.divide(m1,m2)
m6

<tf.Tensor: shape=(), dtype=float64, numpy=0.75>

In [ ]:
m7 = tf.pow(m1,m2)
m7

<tf.Tensor: shape=(), dtype=int32, numpy=81>

In [ ]:
m8 = tf.square(m1)
m8

<tf.Tensor: shape=(), dtype=int32, numpy=9>

In [ ]:
m9= tf.constant ([1,2,3,4,5])
m9

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 2, 3, 4, 5], dtype=int32)>

In [ ]:
m9

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 2, 3, 4, 5], dtype=int32)>